#RASTER_MAKEFILE
CC := cc68x
CCFLAGS := -g
ASLFLAGS := gen -D -L2

TARGET := tst_rast
RASTER_OBJS := rast_asm.o tst_rast.o raster.o

all: $(RASTER_OBJS) $(TARGET)

$(TARGET) : $(RASTER_OBJS)
	$(CC) $(CCFLAGS) $^ -o $(TARGET)

rast_asm.o : rast_asm.s
	$(ASLFLAGS) rast_asm.s

%.o : %.c
	$(CC) $(CCFLAGS) -c %<