#DOUBLE_BUFFERING_MAKEFILE
CC := cc68x
CCFLAGS := -g

EXE := tst_db
OBJS :=  rast_asm.o raster.o input.o sync.o model.o events.o renderer.o douBuf.o

$(EXE) : $(OBJS)
	$(CC) $(CCFLAGS) $^ -o $(EXE)

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

%.o : %.c
	$(CC) $(CCFLAGS) -c %<


