#MUSIC_MAKEFILE
CC := cc68x
CCFLAGS := -g

PSG_EXE := tst
PSG_OBJS :=  music.o psg.o effects.o tstpsg.o

$(PSG_EXE) : $(PSG_OBJS)
	$(CC) $(CCFLAGS) $^ -o $(PSG_EXE)

%.o : %.c
	$(CC) $(CCFLAGS) -c %<


